### ISSUE TITLE
Servo Motors move jerkily, how to improve the movement?

### ISSUE THREAD

**Issue by aaronse** [aaronse/ServoPixelDisplay#8]
hi, I tried your program but the servomotors move jerkily, what can I do to improve the movement of the motors? Furthermore, I would like to slow down the speed of the servomotors, what can I do?

_Originally posted by @Salvolongo in https://github.com/aaronse/ServoPixelDisplay/discussions/2#discussioncomment-8648347_

**Comment by aaronse** [comment]
Hello @Salvolongo!


The issue you're encountering with jerky movements in SG90 9g servo motors, while using PCA9685 PWM servo controller boards, can stem from several factors. Here are common reasons and solutions to improve the movement of the motors:

### 1. Power Supply Issues
- **Problem:** Inadequate or unstable power supply can cause jerky movements. SG90 servos typically operate at 4.8V to 6V, and their performance can significantly degrade if the voltage drops below this range or if the power supply cannot provide sufficient current.
- **Solution:** Ensure your power supply can deliver consistent voltage within the servo's operating range and can handle the current draw of all servos under load. Using a dedicated, high-quality power supply might resolve the issue.

### 2. Signal Interference or Noise
- **Problem:** Electrical noise or interference in the PWM signal from the PCA9685 to the servos can cause erratic movements.
- **Solution:** Use shorter cables to reduce the chance of interference, and consider adding ferrite beads or capacitors to filter out noise. Ensuring solid, clean connections can also help.

### 3. PWM Frequency Mismatch
- **Problem:** The PCA9685 allows you to set the PWM frequency, and if this frequency doesn't match what the servos expect, it can result in jerky movements.
- **Solution:** The SG90 servos typically expect a 50Hz PWM signal. Ensure the PCA9685 is configured to output at this frequency.

### 4. Mechanical Load and Binding
- **Problem:** Mechanical resistance or binding in the servo gears or in the mechanism the servos are driving can cause jerky movements.
- **Solution:** Check for any mechanical issues that might be causing resistance to the servo's movement. Lubricate gears if necessary and ensure that the load on the servo is within its capabilities.

### 5. Software Issues
- **Problem:** The way the PWM signals are being modulated in your code can lead to jerky movements if not done smoothly.
- **Solution:** Implement smoother transitions in your control algorithm. For example, instead of jumping from one position to another instantly, gradually increase the PWM signal to create a smoother motion.

### 6. Servo Quality or Damage
- **Problem:** SG90 servos are inexpensive and can vary in quality. Sometimes, internal damage or wear can cause poor performance.
- **Solution:** Test with another servo to see if the problem persists. If a replacement servo works better, the issue might be with the original servo's quality or condition.

### 7. Calibration Issues
- **Problem:** If the PCA9685's PWM signal doesn't match the servo's expected pulse width for its range of motion, it can cause erratic behavior.
- **Solution:** Calibrate your system by adjusting the PWM signal's pulse width to ensure it aligns with the servo's specifications for minimum and maximum positions.

### Additional Tips:
- **Use External Power:** For multiple servos, it's often recommended to power the servos separately from the logic board to prevent voltage drops and interference.
- **Check for Overloading:** Ensure that the servos are not being overloaded beyond their torque capacity, as this can also cause jerky movements.
- **Update Firmware/Software:** Make sure that the firmware on the PCA9685 and your control software are up to date to benefit from any bug fixes or improvements.

By systematically addressing these potential issues, you should be able to identify and mitigate the cause of the jerky movements in your SG90 servo motors.


Can slow down speed of the servomotors by changing the delay(10); which means wait 10 milliseconds, to a much larger number between updates, maybe try 100 milliseconds, something to experiment with.

https://github.com/aaronse/ServoPixelDisplay/blob/5fcea9af71efd5064f86ff9575d3d690f0de3f88/src/wtd_1/wtd_1.ino#L155

Hope that helps.  Cheers!

**Comment by aaronse** [comment]
Closing this as an issue, and following up in the Q&A /Discussion area instead https://github.com/aaronse/ServoPixelDisplay/discussions/9

**Comment by Salvolongo** [comment]
I tried bringing the delay to 100, the motors move slower but they move jerkily and have a bad effect, I would like to make the movements more fluid, the motors are not attached to anything so they are not overloaded
